### ISSUE TITLE
PAGE_FAULT_IN_NON_PAGED_AREA

### ISSUE THREAD

**Issue by hooktems** [iPower/KasperskyHook#10]
hi,if I map KasperskyDriver.sys then I get a BSOD with an error: PAGE_FAULT_IN_NON_PAGED_AREA.How can i fix it
RU:
Привет,если я смаплю KasperskyHookDriver.sys тогда у меня появляется BSOD с ошибкой: PAGE_FAULT_IN_NON_PAGED_AREA.Как это можно пофиксить?

**Comment by iPower** [comment]
KasperskyHook.sys isn't designed to be manually mapped. You have to update DriverEntry since it expects it is a legit driver.
