### ISSUE TITLE
It seems that this method does not support the latest klhk.sys

### ISSUE THREAD

**Issue by ZRR666** [iPower/KasperskyHook#11]
It seems that this method does not support the latest klhk.sys
The January 19, 2024 version will have a blue screen
An attempt was made to locate the corresponding address

**Comment by recoil23** [comment]
> ![image](https://private-user-images.githubusercontent.com/41984214/305714505-77512bf9-34b3-4eb6-81ca-f32aa9ba9f08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNTM5MDAsIm5iZiI6MTcwOTA1MzYwMCwicGF0aCI6Ii80MTk4NDIxNC8zMDU3MTQ1MDUtNzc1MTJiZjktMzRiMy00ZWI2LTgxY2EtZjMyYWE5YmE5ZjA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDE3MDY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzNzNiZTI4MmY0YTU5MThlODM5Y2YyNTZlMTc3YTgzOWI4N2M3YjhlZDlhNDBiNzQ2ZjlkMjZiZTZmMGExOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fzZ4Kq0I13dAEagN_NFMF9r8kAEFi00vBg_YytOvK18) set_hvm_event is no longer a function but a piece of code

Do you have a fix for that please?

**Comment by recoil23** [comment]
@ZRR666 I mean could we like use some previous build of that driver, hope they dont have hardcoded syscalls vary from 21h1 to 22h2

**Comment by recoil23** [comment]
Alright I've just looked myself into it. Listen cuz we are in a big trouble. They changed their driver code starting from the versions when installer puts it in separate folder named KV. New hypervisor code and some of funcs are inlined now. I was only able to find some new sigs ill share here but the hypervisor got ripped :(

`// Find number of services (SSDT)
presult = utils::find_pattern_km( L"klhk.sys", ".text", "\x89\x05\xCC\xCC\xCC\xCC\x85\xC0", "xx????xx" );`
`// Find number of services (Shadow SSDT)
presult = utils::find_pattern_km( L"klhk.sys", ".text", "\x89\x05\xCC\xCC\xCC\xCC\x85\xC0", "xx????xx" );`
`// Find provider data
presult = utils::find_pattern_km(L"klhk.sys", ".text", "\x89\x1D\xCC\xCC\xCC\xCC\x75\x07", "xx????xx");`

**Comment by iPower** [comment]
Well then just replicate what the function does. It's not like it's hard to do lol.

**Comment by iPower** [comment]
Solved: https://github.com/iPower/KasperskyHook/commit/0a86dd9bb58f1d24e1936f51d34f85ace3e30045
