### ISSUE TITLE
Hello, i have a issue with hvm_thread_object, value is null

### ISSUE THREAD

**Issue by 0x1ffll** [iPower/KasperskyHook#16]
When i reading hvm_thread_object value is null
![image](https://github.com/user-attachments/assets/936897f7-613b-4d12-8625-0a20b9e19088)
In screenshot it: 
"[+] klhk.sys!HVMThreadObject @ 0x0000000000000000"
DbgPrintEx( 0, 0, e( "[+] klhk.sys!HVMThreadObject @ 0x%p\n" ), -* ( uint64_t -* )impl::g_hvm_thread_object ); ( - just because github hide *
I'm on VMWare, Windows 10 22H2, other hypervisors off, HVCI off, antivirus fully unistalled

**Comment by iPower** [comment]
Did you try updating klhk.sys to see if that solves your issue?

**Comment by 0x1ffll** [comment]
Yes, i updated klhk.sys ( 3 june 2024 build ), but have same issue

**Comment by iPower** [comment]
Hmmm I'll take a look when I have some free time.

**Comment by 0x1ffll** [comment]
Fixed, just need to wait 5 mins because kaspersky initializing

**Comment by 271135861** [comment]
Did you find the problem? I have the same problem.

**Comment by providence121** [comment]
Virtualization is working after installing Kaspersky application

**Comment by iPower** [comment]
Did you try following the troubleshooting steps? Try installing Kaspersky, maybe some settings changed. Haven't had a chance to take a look yet because I'm too busy with work.
