### ISSUE TITLE
win 11 and last Driver test failed.

### ISSUE THREAD

**Issue by ashyerv** [iPower/KasperskyHook#9]
VM: Install Kaspersky (get new driver)
code:
fix ssdt_service_count (change sig) (old sig boken, i fixed。 got 3 version klhk.sys , only here no change .)

`presult = utils::find_pattern_km(L"klhk.sys", ".text", "\x83\xE1\x01\x75\x27", "xxxxx");
if (!presult)
		return false;
	presult = presult + 0xE;`

test , and again return **C000090B** (include VM return C000090B)
...emmmm any update or etc?

[klhk.zip](https://github.com/iPower/KasperskyHook/files/8349399/klhk.zip)

**Comment by hooktems** [comment]
hi, new sig in this source - https://github.com/alexcard144803/KasperskyHook_NewKSDriver/blob/main/KasperskyHookDrv/kaspersky.cpp

**Comment by ashyerv** [comment]
> 

sry ,.i can't help you..
i haven't met
only the sig changed. fixit but set_hvm_event() return C000090B,
can't work.
even though use last klhk.sys  again....

**Comment by iPower** [comment]
That might be because this klhk.sys version doesn't support your Windows 11 build. Kaspersky has a hardcoded table for Shadow SSDT so that might be the issue.

**Comment by ashyerv** [comment]
> That might be because this klhk.sys version doesn't support your Windows 11 build. Kaspersky has a hardcoded table for Shadow SSDT so that might be the issue.

maybe ...no ? hooking NtCreateFile , if start driver . will give me`**set_hvm_event() return C000090B**, like ckeck some no started. i use auto get ssdt index (not shadow ssdt)..

**Comment by iPower** [comment]
If you take a look at klhk.sys initialization it fails if your Windows build isn't present in their Shadow SSDT hardcoded table.

**Comment by ashyerv** [comment]
> If you take a look at klhk.sys initialization it fails if your Windows build isn't present in their Shadow SSDT hardcoded table.

oh,.ok ,thanks you help , have nice day :)

**Comment by iPower** [comment]
Btw thanks for letting me know that the sig is outdated! I'm updating it right now
